import BeautifulWallet from '../BeautifulWallet'

export default [
    new BeautifulWallet(/^0x0123456/i, "starts with number ascendant", true),
    new BeautifulWallet(/^0xabcdef/i, "starts with alphabet ascendant", true),
    new BeautifulWallet(/^0x\d{40}$/i, "only numbers", true),
    new BeautifulWallet(/^0x[a-f]{40}$/i, "only alphabets", true),

    new BeautifulWallet(/^0xf{8}/i, "starts with more than seven F", true),
    new BeautifulWallet(/^0xe{8}/i, "starts with more than seven E", true),
    new BeautifulWallet(/^0xd{8}/i, "starts with more than seven D", true),
    new BeautifulWallet(/^0xc{8}/i, "starts with more than seven C", true),
    new BeautifulWallet(/^0xb{8}/i, "starts with more than seven B", true),
    new BeautifulWallet(/^0xa{8}/i, "starts with more than seven A", true),
    new BeautifulWallet(/^0x9{8}/i, "starts with more than seven nines", true),
    new BeautifulWallet(/^0x8{8}/i, "starts with more than seven eights", true),
    new BeautifulWallet(/^0x7{8}/i, "starts with more than seven sevens", true),
    new BeautifulWallet(/^0x6{8}/i, "starts with more than seven sixes", true),
    new BeautifulWallet(/^0x5{8}/i, "starts with more than seven fives", true),
    new BeautifulWallet(/^0x4{8}/i, "starts with more than seven fours", true),
    new BeautifulWallet(/^0x3{8}/i, "starts with more than seven threes", true),
    new BeautifulWallet(/^0x2{8}/i, "starts with more than seven twos", true),
    new BeautifulWallet(/^0x1{8}/i, "starts with more than seven ones", true),
    new BeautifulWallet(/^0x0{8}/i, "starts with more than seven zeros", true),
    new BeautifulWallet(/^0xf{7}[^f]/i, "starts with seven F", true),
    new BeautifulWallet(/^0xe{7}[^e]/i, "starts with seven E", true),
    new BeautifulWallet(/^0xd{7}[^d]/i, "starts with seven D", true),
    new BeautifulWallet(/^0xc{7}[^c]/i, "starts with seven C", true),
    new BeautifulWallet(/^0xb{7}[^b]/i, "starts with seven B", true),
    new BeautifulWallet(/^0xa{7}[^a]/i, "starts with seven A", true),
    new BeautifulWallet(/^0x9{7}[^9]/i, "starts with seven nines", true),
    new BeautifulWallet(/^0x8{7}[^8]/i, "starts with seven eights", true),
    new BeautifulWallet(/^0x7{7}[^7]/i, "starts with seven sevens", true),
    new BeautifulWallet(/^0x6{7}[^6]/i, "starts with seven sixes", true),
    new BeautifulWallet(/^0x5{7}[^5]/i, "starts with seven fives", true),
    new BeautifulWallet(/^0x4{7}[^4]/i, "starts with seven fours", true),
    new BeautifulWallet(/^0x3{7}[^3]/i, "starts with seven threes", true),
    new BeautifulWallet(/^0x2{7}[^2]/i, "starts with seven twos", true),
    new BeautifulWallet(/^0x1{7}[^1]/i, "starts with seven ones", true),
    new BeautifulWallet(/^0x0{7}[^0]/i, "starts with seven zeros", true),
    new BeautifulWallet(/^0xf{6}[^f]/i, "starts with six F", true),
    new BeautifulWallet(/^0xe{6}[^e]/i, "starts with six E", true),
    new BeautifulWallet(/^0xd{6}[^d]/i, "starts with six D", true),
    new BeautifulWallet(/^0xc{6}[^c]/i, "starts with six C", true),
    new BeautifulWallet(/^0xb{6}[^b]/i, "starts with six B", true),
    new BeautifulWallet(/^0xa{6}[^a]/i, "starts with six A", true),
    new BeautifulWallet(/^0x9{6}[^9]/i, "starts with six nines", true),
    new BeautifulWallet(/^0x8{6}[^8]/i, "starts with six eights", true),
    new BeautifulWallet(/^0x7{6}[^7]/i, "starts with six sevens", true),
    new BeautifulWallet(/^0x6{6}[^6]/i, "starts with six sixes", true),
    new BeautifulWallet(/^0x5{6}[^5]/i, "starts with six fives", true),
    new BeautifulWallet(/^0x4{6}[^4]/i, "starts with six fours", true),
    new BeautifulWallet(/^0x3{6}[^3]/i, "starts with six threes", true),
    new BeautifulWallet(/^0x2{6}[^2]/i, "starts with six twos", true),
    new BeautifulWallet(/^0x1{6}[^1]/i, "starts with six ones", true),
    new BeautifulWallet(/^0x0{6}[^0]/i, "starts with six zeros", true),
    new BeautifulWallet(/^0xf{5}[^f]/i, "starts with five F", true),
    new BeautifulWallet(/^0xe{5}[^e]/i, "starts with five E", true),
    new BeautifulWallet(/^0xd{5}[^d]/i, "starts with five D", true),
    new BeautifulWallet(/^0xc{5}[^c]/i, "starts with five C", true),
    new BeautifulWallet(/^0xb{5}[^b]/i, "starts with five B", true),
    new BeautifulWallet(/^0xa{5}[^a]/i, "starts with five A", true),
    new BeautifulWallet(/^0x9{5}[^9]/i, "starts with five nines", true),
    new BeautifulWallet(/^0x8{5}[^8]/i, "starts with five eights", true),
    new BeautifulWallet(/^0x7{5}[^7]/i, "starts with five sevens", true),
    new BeautifulWallet(/^0x6{5}[^6]/i, "starts with five sixes", true),
    new BeautifulWallet(/^0x5{5}[^5]/i, "starts with five fives", true),
    new BeautifulWallet(/^0x4{5}[^4]/i, "starts with five fours", true),
    new BeautifulWallet(/^0x3{5}[^3]/i, "starts with five threes", true),
    new BeautifulWallet(/^0x2{5}[^2]/i, "starts with five twos", true),
    new BeautifulWallet(/^0x1{5}[^1]/i, "starts with five ones", true),
    new BeautifulWallet(/^0x0{5}[^0]/i, "starts with five zeros", true),
    new BeautifulWallet(/^0xf{4}[^f]/i, "starts with four F", true),
    new BeautifulWallet(/^0xe{4}[^e]/i, "starts with four E", true),
    new BeautifulWallet(/^0xd{4}[^d]/i, "starts with four D", true),
    new BeautifulWallet(/^0xc{4}[^c]/i, "starts with four C", true),
    new BeautifulWallet(/^0xb{4}[^b]/i, "starts with four B", true),
    new BeautifulWallet(/^0xa{4}[^a]/i, "starts with four A", true),
    new BeautifulWallet(/^0x9{4}[^9]/i, "starts with four nines", true),
    new BeautifulWallet(/^0x8{4}[^8]/i, "starts with four eights", true),
    new BeautifulWallet(/^0x7{4}[^7]/i, "starts with four sevens", true),
    new BeautifulWallet(/^0x6{4}[^6]/i, "starts with four sixes", true),
    new BeautifulWallet(/^0x5{4}[^5]/i, "starts with four fives", true),
    new BeautifulWallet(/^0x4{4}[^4]/i, "starts with four fours", true),
    new BeautifulWallet(/^0x3{4}[^3]/i, "starts with four threes", true),
    new BeautifulWallet(/^0x2{4}[^2]/i, "starts with four twos", true),
    new BeautifulWallet(/^0x1{4}[^1]/i, "starts with four ones", true),
    new BeautifulWallet(/^0x0{4}[^0]/i, "starts with four zeros", true),

    new BeautifulWallet(/f{7}$/i, "ends with more than seven F", true),
    new BeautifulWallet(/e{7}$/i, "ends with more than seven E", true),
    new BeautifulWallet(/d{7}$/i, "ends with more than seven D", true),
    new BeautifulWallet(/c{7}$/i, "ends with more than seven C", true),
    new BeautifulWallet(/b{7}$/i, "ends with more than seven B", true),
    new BeautifulWallet(/a{7}$/i, "ends with more than seven A", true),
    new BeautifulWallet(/9{7}$/i, "ends with more than seven nines", true),
    new BeautifulWallet(/8{7}$/i, "ends with more than seven eights", true),
    new BeautifulWallet(/7{7}$/i, "ends with more than seven sevens", true),
    new BeautifulWallet(/6{7}$/i, "ends with more than seven sixes", true),
    new BeautifulWallet(/5{7}$/i, "ends with more than seven fives", true),
    new BeautifulWallet(/4{7}$/i, "ends with more than seven fours", true),
    new BeautifulWallet(/3{7}$/i, "ends with more than seven threes", true),
    new BeautifulWallet(/2{7}$/i, "ends with more than seven twos", true),
    new BeautifulWallet(/1{7}$/i, "ends with more than seven ones", true),
    new BeautifulWallet(/0{7}$/i, "ends with more than seven zeros", true),
    new BeautifulWallet(/[^f]f{7}$/i, "ends with seven F", true),
    new BeautifulWallet(/[^e]e{7}$/i, "ends with seven E", true),
    new BeautifulWallet(/[^d]d{7}$/i, "ends with seven D", true),
    new BeautifulWallet(/[^c]c{7}$/i, "ends with seven C", true),
    new BeautifulWallet(/[^b]b{7}$/i, "ends with seven B", true),
    new BeautifulWallet(/[^a]a{7}$/i, "ends with seven A", true),
    new BeautifulWallet(/[^9]9{7}$/i, "ends with seven nines", true),
    new BeautifulWallet(/[^8]8{7}$/i, "ends with seven eights", true),
    new BeautifulWallet(/[^7]7{7}$/i, "ends with seven sevens", true),
    new BeautifulWallet(/[^6]6{7}$/i, "ends with seven sixes", true),
    new BeautifulWallet(/[^5]5{7}$/i, "ends with seven fives", true),
    new BeautifulWallet(/[^4]4{7}$/i, "ends with seven fours", true),
    new BeautifulWallet(/[^3]3{7}$/i, "ends with seven threes", true),
    new BeautifulWallet(/[^2]2{7}$/i, "ends with seven twos", true),
    new BeautifulWallet(/[^1]1{7}$/i, "ends with seven ones", true),
    new BeautifulWallet(/[^0]0{7}$/i, "ends with seven zeros", true),
    new BeautifulWallet(/[^f]f{6}$/i, "ends with six F", true),
    new BeautifulWallet(/[^e]e{6}$/i, "ends with six E", true),
    new BeautifulWallet(/[^d]d{6}$/i, "ends with six D", true),
    new BeautifulWallet(/[^c]c{6}$/i, "ends with six C", true),
    new BeautifulWallet(/[^b]b{6}$/i, "ends with six B", true),
    new BeautifulWallet(/[^a]a{6}$/i, "ends with six A", true),
    new BeautifulWallet(/[^9]9{6}$/i, "ends with six nines", true),
    new BeautifulWallet(/[^8]8{6}$/i, "ends with six eights", true),
    new BeautifulWallet(/[^7]7{6}$/i, "ends with six sevens", true),
    new BeautifulWallet(/[^6]6{6}$/i, "ends with six sixes", true),
    new BeautifulWallet(/[^5]5{6}$/i, "ends with six fives", true),
    new BeautifulWallet(/[^4]4{6}$/i, "ends with six fours", true),
    new BeautifulWallet(/[^3]3{6}$/i, "ends with six threes", true),
    new BeautifulWallet(/[^2]2{6}$/i, "ends with six twos", true),
    new BeautifulWallet(/[^1]1{6}$/i, "ends with six ones", true),
    new BeautifulWallet(/[^0]0{6}$/i, "ends with six zeros", true),
    new BeautifulWallet(/[^f]f{5}$/i, "ends with five F", true),
    new BeautifulWallet(/[^e]e{5}$/i, "ends with five E", true),
    new BeautifulWallet(/[^d]d{5}$/i, "ends with five D", true),
    new BeautifulWallet(/[^c]c{5}$/i, "ends with five C", true),
    new BeautifulWallet(/[^b]b{5}$/i, "ends with five B", true),
    new BeautifulWallet(/[^a]a{5}$/i, "ends with five A", true),
    new BeautifulWallet(/[^9]9{5}$/i, "ends with five nines", true),
    new BeautifulWallet(/[^8]8{5}$/i, "ends with five eights", true),
    new BeautifulWallet(/[^7]7{5}$/i, "ends with five sevens", true),
    new BeautifulWallet(/[^6]6{5}$/i, "ends with five sixes", true),
    new BeautifulWallet(/[^5]5{5}$/i, "ends with five fives", true),
    new BeautifulWallet(/[^4]4{5}$/i, "ends with five fours", true),
    new BeautifulWallet(/[^3]3{5}$/i, "ends with five threes", true),
    new BeautifulWallet(/[^2]2{5}$/i, "ends with five twos", true),
    new BeautifulWallet(/[^1]1{5}$/i, "ends with five ones", true),
    new BeautifulWallet(/[^0]0{5}$/i, "ends with five zeros", true),
    new BeautifulWallet(/[^f]f{4}$/i, "ends with four F", true),
    new BeautifulWallet(/[^e]e{4}$/i, "ends with four E", true),
    new BeautifulWallet(/[^d]d{4}$/i, "ends with four D", true),
    new BeautifulWallet(/[^c]c{4}$/i, "ends with four C", true),
    new BeautifulWallet(/[^b]b{4}$/i, "ends with four B", true),
    new BeautifulWallet(/[^a]a{4}$/i, "ends with four A", true),
    new BeautifulWallet(/[^9]9{4}$/i, "ends with four nines", true),
    new BeautifulWallet(/[^8]8{4}$/i, "ends with four eights", true),
    new BeautifulWallet(/[^7]7{4}$/i, "ends with four sevens", true),
    new BeautifulWallet(/[^6]6{4}$/i, "ends with four sixes", true),
    new BeautifulWallet(/[^5]5{4}$/i, "ends with four fives", true),
    new BeautifulWallet(/[^4]4{4}$/i, "ends with four fours", true),
    new BeautifulWallet(/[^3]3{4}$/i, "ends with four threes", true),
    new BeautifulWallet(/[^2]2{4}$/i, "ends with four twos", true),
    new BeautifulWallet(/[^1]1{4}$/i, "ends with four ones", true),
    new BeautifulWallet(/[^0]0{4}$/i, "ends with four zeros", true),
]