export type BeautifulWallet = {
    addressPattern: RegExp
    description: string
    active: true
}

export const beautifulWallets: BeautifulWallet[] = [
    { addressPattern: /^0x\d{40}$/i, description: "only numbers", active: true },
    { addressPattern: /^0x[a-f]{40}$/i, description: "only alphabets", active: true },
    { addressPattern: /^0x0{7}/i, description: "starts with 7 zeros", active: true },
    { addressPattern: /^0x1{7}/i, description: "starts with 7 ones", active: true },
    { addressPattern: /^0x2{7}/i, description: "starts with 7 twos", active: true },
    { addressPattern: /^0x3{7}/i, description: "starts with 7 threes", active: true },
    { addressPattern: /^0x4{7}/i, description: "starts with 7 fours", active: true },
    { addressPattern: /^0x5{7}/i, description: "starts with 7 fives", active: true },
    { addressPattern: /^0x6{7}/i, description: "starts with 7 sixes", active: true },
    { addressPattern: /^0x7{7}/i, description: "starts with 7 sevens", active: true },
    { addressPattern: /^0x8{7}/i, description: "starts with 7 eights", active: true },
    { addressPattern: /^0x9{7}/i, description: "starts with 7 nines", active: true },
    { addressPattern: /^0xa{7}/i, description: "starts with 7 a", active: true },
    { addressPattern: /^0xb{7}/i, description: "starts with 7 b", active: true },
    { addressPattern: /^0xc{7}/i, description: "starts with 7 c", active: true },
    { addressPattern: /^0xd{7}/i, description: "starts with 7 d", active: true },
    { addressPattern: /^0xe{7}/i, description: "starts with 7 e", active: true },
    { addressPattern: /^0xf{7}/i, description: "starts with 7 f", active: true },
    { addressPattern: /^0x0000[0-9a-f]{32}0000$/i, description: "lead and tail are 4 zeros", active: true },
    { addressPattern: /^0x[0369a-f]{40}$/i, description: "multiple of 3", active: true },
    { addressPattern: /^0x0123456/i, description: "starts with number ascendant", active: true },
    { addressPattern: /3456789^/i, description: "ends with number descendant", active: true },
    { addressPattern: /0{8}/i, description: "includes 8 zeros", active: true },
    { addressPattern: /1{8}/i, description: "includes 8 ones", active: true },
    { addressPattern: /2{8}/i, description: "includes 8 twos", active: true },
    { addressPattern: /3{8}/i, description: "includes 8 threes", active: true },
    { addressPattern: /4{8}/i, description: "includes 8 fours", active: true },
    { addressPattern: /5{8}/i, description: "includes 8 fives", active: true },
    { addressPattern: /6{8}/i, description: "includes 8 sixes", active: true },
    { addressPattern: /7{8}/i, description: "includes 8 sevens", active: true },
    { addressPattern: /8{8}/i, description: "includes 8 eights", active: true },
    { addressPattern: /9{8}/i, description: "includes 8 nines", active: true },
    { addressPattern: /a{8}/i, description: "includes 8 a", active: true },
    { addressPattern: /b{8}/i, description: "includes 8 b", active: true },
    { addressPattern: /c{8}/i, description: "includes 8 c", active: true },
    { addressPattern: /d{8}/i, description: "includes 8 d", active: true },
    { addressPattern: /e{8}/i, description: "includes 8 e", active: true },
    { addressPattern: /f{8}/i, description: "includes 8 f", active: true },
]